---
subtitle: "TMA4268 Statistical Learning V2022"
title: "Compulsory exercise 1: Group 16"
author: "Weicheng Hua, Emil Johannesen Haugstvedt, Torbjørn Baadsvik"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    toc: true
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,message=FALSE,warning=FALSE,strip.white=TRUE,prompt=FALSE,
                      cache=TRUE, size="scriptsize",fig.width=4, fig.height=3,fig.align = "center")

```

```{r,eval=TRUE,echo=FALSE}
library("knitr")
library("rmarkdown")
```

\section{Problem 1}

\subsection{a)}

\subsection{b)}

\subsection{c)}

\subsection{d)}

\section{Problem 2}

\subsection{a)}

\subsection{b)}

\section{Problem 3}

\subsection{a)}

\subsection{b)}

\section{Problem 4}

\subsection{a)}

\subsection{b)}

\subsection{c)}

\subsection{d)}

\section{Problem 5}

\subsection{a)}

\subsection{b)}

\section{Problem 6}

\subsection{a)}

\subsection{b)}

\subsection{c)}

\subsection{d)}
